### ISSUE TITLE
Shortcuts for press and release

### ISSUE THREAD

**Issue by seeeeew** [TiBeN/shortcutd#1]
Would it be possible to run different commands on press and release of a certain key/button/shortcut? This would allow me to start something on press and stop it on release, basically running it while the shortcut is pressed.

**Comment by TiBeN** [comment]
Hi, this ils not possible for now but couldn't be hard to implement. I'll take a look at it asap.

**Comment by seeeeew** [comment]
You were right, it was pretty easy to implement after all. (See PRs #2/#3.)
